export const PERSON_PLUS_ONE = 'PERSON_PLUS_ONE';
export const PERSON_MINUS_ONE = 'PERSON_MINUS_ONE';
export const PERSON_RESET = 'PERSON_RESET';
export const HOME_PERSON_PLUS_ONE = 'HOME_PERSON_PLUS_ONE';
export const HOME_PERSON_MINUS_ONE = 'HOME_PERSON_MINUS_ONE';
export const HOME_PERSON_RESET = 'HOME_PERSON_RESET';